name: shell script workflow

on: workflow_dispatch

jobs:
  running-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-script
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "make the script executable"
        run: |
          pwd
          ls -la
          git status
          chmod +x test.sh
          ls -la
      - name: "run script"
        run: |
          pwd
          ls -la
          ./test.sh
