# This is a basic workflow to help you get started with Actions

name: Expression Testing
# Controls when the workflow will run
on:
  pull_request:
    branches:
      - 'releases/**'
      - '!releases/**-alpha'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  expression-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Format String
        run: echo "${{ format('Hello {0} you''re inside {1} {2}', '$GITHUB_ACTOR', 'github.workflow', '$GITHUB_REF') }}"
      - name: Hash file
        run: echo ${{ hashFiles('/.github/**/*.yml')}}
